### PR TITLE
Configure license from $PRINCE_LICENSE

### PR DESCRIPTION
**Pull request by andrewgarner**

### CODE REVIEW

**Comment by gjvis** [comment]
Is the intention here that you'd check the licence file into source control?

**Comment by andrewgarner** [comment]
The contents of the `license.dat` file issued by PrinceXML are stored in the Heroku config variable `PRINCE_LICENSE`. This is then available to the buildpack when the dyno is built.

**Comment by gjvis** [comment]
That's not what this PR does though?

**Comment by gjvis** [comment]
[This PR](https://github.com/lm-tools/heroku-buildpack-princexml/pull/2/files) (which Steve cancelled) looks like it would do what you're describing.

**Comment by andrewgarner** [comment]
The Heroku config vars are passed to the buildpack and written to `ENV_DIR` which is `$3` - https://devcenter.heroku.com/articles/buildpack-api#bin-compile

**Comment by gjvis** [comment]
everyday is a learning day :dancer:

**Comment by modsognir** [comment]
Was just about to put up a PR like this. Thanks!

**Pull request merged**
